name: fallow-ci
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  fallow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v7

      - name: Run Fallow analysis
        uses: fallow-rs/fallow@v2
        with:
          workspace: serverless-s3-web-app
          comment: true
